theme:
    name: material
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - navigation.expand  # Expand collapsible sections by default
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right


site_name: bayesnf
site_description: The documentation for the bayesnf software library.
site_author: Colin Carroll
site_url: https://google.github.io/bayesnf

repo_url: https://github.com/google/bayesnf
repo_name: google/bayesnf
edit_uri: ""

# Do not allow warnings during the build process
strict: true

# Detect changes in the src/ code.
watch:
    - README.md
    - src

extra_javascript:
    # https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - _static/custom.css

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.snippets  # Allowing hidden expandable regions denoted by ???
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???
    - admonition
    - toc:
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

plugins:
    # https://www.mkdocs.org/dev-guide/plugins/
    - search
    - autorefs  # https://github.com/mkdocstrings/autorefs
    - mkdocstrings:
        default_handler: python
        handlers:
            python:
                paths: src
                options:
                    # https://mkdocstrings.github.io/python/usage/
                    show_symbol_type_heading: true
                    show_symbol_type_toc: true
                    show_root_full_path: false
                    show_if_no_docstring: false
                    show_signature_annotations: false
                    show_source: true
                    members_order: source
                    heading_level: 4
                    line_length: 120
                    separate_signature: true
                    line_length: 50
                    docstring_section_style: spacy

nav:
    - Home: 'index.md'
    - API:
        - 'api/BayesianNeuralFieldEstimator.md'
        - 'api/BayesianNeuralFieldVI.md'
        - 'api/BayesianNeuralFieldMAP.md'
        - 'api/BayesianNeuralFieldMLE.md'
    - Tutorials:
        - Hungarian Chickenpox: 'tutorials/BayesNF_Tutorial_on_Hungarian_Chickenpox.md'
        - London Air Quality: 'tutorials/BayesNF_Tutorial_on_London_Air_Quality.md'
